
const 
  gulp = require('gulp'),
  liveReloadBP = require("live-reload-bp"),
  plumber = require('gulp-plumber'),
  gulpSass = require('gulp-sass')(require('sass')),
  postcss = require('gulp-postcss'),
  cssnano = require('cssnano'),
  minifyJS = require('gulp-uglify-es').default,
  htmlmin = require('gulp-htmlmin'),
  webServer = require('./web-server');

const 
  cssMain1Watch = 'src/scss/main-1/*.scss',
  cssMain1Src = ['src/scss/main-1/*.scss'],
  cssMain1Dest = 'dest/css';

const 
  cssMain2Watch = 'src/scss/main-2/*.scss',
  cssMain2Src = ['src/scss/main-2/*.scss'],
  cssMain2Dest = 'dest/css';

const 
  htmlWatch = 'src/*.html',
  htmlSrc = ['src/*.html'],
  htmlDest = 'dest';

const 
  jsWatch = 'src/js/*.js',
  jsSrc = ['src/js/*.js'],
  jsDest = 'dest/js';

const 
  liveReload = new liveReloadBP({
    host: '127.0.0.1', 
    port: '8080'
  });


function cssMain1() {
  return gulp.src(cssMain1Src)
  .pipe(plumber())        
  .pipe(gulpSass().on('error', gulpSass.logError))   
  .pipe(postcss([
    cssnano({zindex: false, reduceIdents: false})
  ]))     
  .pipe(gulp.dest(cssMain1Dest));
}


function cssMain2() {
  return gulp.src(cssMain2Src)
  .pipe(plumber())        
  .pipe(gulpSass().on('error', gulpSass.logError))   
  .pipe(postcss([
    cssnano({zindex: false, reduceIdents: false})
  ]))     
  .pipe(gulp.dest(cssMain2Dest));
}


function html() {
  return gulp.src(htmlSrc)    
  .pipe(plumber())
  .pipe(htmlmin({
    collapseWhitespace: true,
    removeComments: true,
    removeScriptTypeAttributes: true,
    includeAutoGeneratedTags: false,
    ignoreCustomComments: [
      /^noindex/,
      /\/noindex+$/
    ], 
    minifyJS: false,
    minifyCSS: false,
    trimCustomFragments: true,
    //ignoreCustomFragments: [ (/\{\%[^\%]*?\%\}(\s)?/g) ],
  }))
  .pipe(gulp.dest(htmlDest));
}


function js(){
  return gulp.src(jsSrc)
  .pipe(minifyJS()) 
  .pipe(gulp.dest(jsDest));
}


function reloadCssMain1(cb){
  liveReload.reloadPage({
    action: 'page_reload',
    partial_reload: {
      tag: 'link',    
      href: '/css/1.css'
    }      
  });

  cb();
}


function reloadCssMain2(cb){
  liveReload.reloadPage({
    action: 'page_reload',
    partial_reload: {
      tag: 'link',    
      href: '/css/2.css'
    }      
  });

  cb();
}


function reloadHtml(cb){
  liveReload.reloadPage({
    action: 'page_reload',
    partial_reload: {
      tag: 'html',    
      html: {
        force_load_images: false // Usually, images are taken from the browser cache when the HTML is partially reloaded.
      }
    }      
  });

  cb();
}


function reloadJs(cb){
  let before = function(){
    let $script1 = document.getElementById("script1");
    if($script1 != null){
        $script1.innerHTML = '';
    }
  }.toString();

  liveReload.reloadPage({
    action: 'page_reload',
    partial_reload: {
      tag: 'script',    
      src: '/js/1.js',
      execute_before: before,
      js: {
        //clear_obsolete_tags: ['style'],
        //resetHTML: false,
        use_method_1: {
          send_event_onload: true
        }        
      }
    }      
  });

  cb();
}


function watch(){
  liveReload.run();
  webServer();

  // CSS
  gulp.watch(cssMain1Watch, gulp.series(cssMain1, reloadCssMain1));
  gulp.watch(cssMain2Watch, gulp.series(cssMain2, reloadCssMain2));

  // HTML
  gulp.watch(htmlWatch, gulp.series(html, reloadHtml));

  // JS
  gulp.watch(jsWatch, gulp.series(js, reloadJs));
}


exports.cssMain1 = cssMain1;
exports.cssMain2 = cssMain2;
exports.html = html;
exports.js = js;
exports.watch = watch;
exports.reloadCssMain1 = reloadCssMain1;
exports.reloadCssMain2 = reloadCssMain2;
exports.reloadJs = reloadJs;
exports.reloadHtml = reloadHtml;
exports.start = gulp.series(cssMain1, cssMain2, html, js, watch);
