
const 
  gulp = require('gulp'),
  liveReloadBP = require("live-reload-bp"),
  plumber = require('gulp-plumber'),
  gulpSass = require('gulp-sass')(require('sass')),
  postcss = require('gulp-postcss'),
  cssnano = require('cssnano'),
  minifyJS = require('gulp-uglify-es').default,
  htmlmin = require('gulp-htmlmin'),
  webServer = require('./web-server');

const 
  cssWatch = 'src/scss/*.scss',
  cssSrc = ['src/scss/*.scss'],
  cssDest = 'dest/css';

const 
  htmlWatch = 'src/*.html',
  htmlSrc = ['src/*.html'],
  htmlDest = 'dest';

const 
  jsWatch = 'src/js/*.js',
  jsSrc = ['src/js/*.js'],
  jsDest = 'dest/js';

const 
  liveReload = new liveReloadBP({
    host: '127.0.0.1', 
    port: '8080'
  });


function css() {
  return gulp.src(cssSrc)
  .pipe(plumber())        
  .pipe(gulpSass().on('error', gulpSass.logError))   
  .pipe(postcss([
      cssnano({zindex: false, reduceIdents: false})
  ]))     
  .pipe(gulp.dest(cssDest));
}


function html() {
  return gulp.src(htmlSrc)    
  .pipe(plumber())
  .pipe(htmlmin({
    collapseWhitespace: true,
    removeComments: true,
    removeScriptTypeAttributes: true,
    includeAutoGeneratedTags: false,
    ignoreCustomComments: [
      /^noindex/,
      /\/noindex+$/
    ], 
    minifyJS: false,
    minifyCSS: false,
    trimCustomFragments: true,
    //ignoreCustomFragments: [ (/\{\%[^\%]*?\%\}(\s)?/g) ],
  }))
  .pipe(gulp.dest(htmlDest));
}


function js(){
  return gulp.src(jsSrc)
  .pipe(minifyJS()) 
  .pipe(gulp.dest(jsDest));
}


function reloadPage(cb){
  liveReload.reloadPage();

  cb();
}


function watch(){
  liveReload.run();
  webServer();

  gulp.watch(cssWatch, gulp.series(css, reloadPage));
  gulp.watch(htmlWatch, gulp.series(html, reloadPage));
  gulp.watch(jsWatch, gulp.series(js, reloadPage));
}


exports.css = css;
exports.html = html;
exports.js = js;
exports.watch = watch;
exports.reloadPage = reloadPage;
exports.start = gulp.series(css, html, js, watch);
